package me.ilizin.certification.lambdaexpression;

import java.util.*;

public class LambdaExpression {

    static record Car(String company, int year, double price, String type) {
        public String toString() {  return "(" + company + " " + year + ")"; }
    }

    static interface CarFilter {
        boolean showCar(Car car);
    }

    static class CarMall {
        List<Car> cars = new ArrayList<>();

        CarMall() {
            cars.add(new Car("Honda", 2012, 9000.0, "HATCH"));
            cars.add(new Car("Honda", 2018, 17000.0, "SEDAN"));
            cars.add(new Car("Toyota", 2014, 19000.0, "SUV"));
            cars.add(new Car("Ford", 2014, 13000.0, "SPORTS"));
            cars.add(new Car("Nissan", 2017, 8000.0, "SUV"));
        }

        List<Car> showCars(CarFilter cf) {
            ArrayList<Car> carsToShow = new ArrayList<>();
            for (Car c : cars) {
                if (cf.showCar(c)) carsToShow.add(c);
            }
            return carsToShow;
        }
    }

    static class CompanyFilter implements CarFilter {
        private String company;

        public CompanyFilter(String c) {
            this.company = c;
        }
        public boolean showCar(Car c) {
            return company.equals(c.company());
        }
    }

    public static void main(String[] args) {

        /* We want to get the details of all cars from a particular company.
        To do that, we define a CompanyFilter class that contains the actual logic for filtering cars based
        on company name. At run time, it creates a CompanyFilter object and passes it to CarMall's showCars method,
        which returns a filtered list of cars. */
        CarMall cm = new CarMall();
        CarFilter cf = new CompanyFilter("Honda");
        List<Car> carsByCompany = cm.showCars(cf);
        System.out.println(carsByCompany);

        /* Now look at the following code that uses a lambda expression.
        There is no separate class that implements CarFilter and there is no explicit instantiation
        of a CarFilter object either. Both of these tasks have been replaced by a very short statement
        c -> c.company.equals("Honda"). The lambda expression is just a shortcut for the compiler. */
        cm = new CarMall();
        carsByCompany = cm.showCars(c -> c.company.equals("Honda"));
        System.out.println(carsByCompany);

        /* All the information that is required to do the expansion is available in the context of cm.showCars(...)
        method. The compiler knows that it must pass an object of a class that implements CarFilter
        to the showCars(CarFilter cf) method. It knows that this class must implement the boolean showCar(Car c)
        method because that is the only abstract method declared in the CarFilter interface. The compiler gathers
        from the signature of this method that this method receives an argument of type Car and returns a boolean.
        From this information, it can easily generate the following code on its own:

        //assume that this fictional class is created by the compiler.
        class XYZ implements CarFilter {
        public boolean showCar(Car <<parameterName>>) {
            return <<an expression that returns a boolean must appear here>>;
        }

        The lambda expression does not specify the method name, the parameter types, and the return type.
        The compiler infers these three pieces of information from the context in which you put the lambda expression.
        Thus, a lambda expression must exist within a context that can supply all this information.

        The compiler must also create a class to put that method in. Since a lambda expression has no name,
        the class must be such that it requires implementation of exactly one abstract method whose name the compiler
        can use for the generated method. The only way this can happen is if the class generated by the compiler
        implements an interface with exactly one abstract method or extends an abstract class with exactly one abstract
        method. If the interface or the class has more than one abstract method or no abstract method,
        the compiler wouldn't know which method the code in the lambda expression belongs to.
        Java language designers decided not to allow lambda expressions for abstract classes to reduce complexity.

        The interface should the generated class implement depends on the context.
        The type that the context expects is described as the "target type" and is the interface that the class generated
        by the compiler must implement. In the above code, the showCars method expects a CarFilter object (i.e. object
        of a class that implements CarFilter). Therefore, the generated class must implement CarFilter.

        A lambda expression can be written only where the target type is an interface with exactly one abstract method,
        and Java has a special name for such an interface: Functional Interface. */

        /* Before lambda expression were introduced in Java, people used anonymous classes to achieve the same.
          The following is how you could implement a CarFilter the old way: */
        carsByCompany = cm.showCars(new CarFilter(){
            public boolean showCar(Car c){
                return "Honda".equals(c.company());
            }
        });
    }
}
